import logging
from datetime import datetime
from deep_research.agent import create_agent

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class DeepResearchService:
    def __init__(self, llm, search_engine):
        logger.info("🔬 Initializing DeepResearchService...")
        logger.info(f"  LLM: {llm.model_name if hasattr(llm, 'model_name') else type(llm)}")
        logger.info(f"  Search engine: {type(search_engine)}")
        self.agent = create_agent(llm, search_engine)
        logger.info("✅ DeepResearchService initialized")
        
    def run(self, query: str) -> str:
        logger.info(f"🚀 Starting deep research for query: {query[:100]}...")
        initial_agent_state = {
            'date': datetime.now().strftime('%Y-%m-%d'),
            'search_num': 3,
            'question': query,
        }
        logger.info(f"📋 Initial agent state: date={initial_agent_state['date']}, search_num={initial_agent_state['search_num']}")
        
        try:
            logger.info("🔄 Invoking LangGraph agent...")
            final_state = self.agent.invoke(initial_agent_state)
            logger.info(f"✅ Agent completed. Final state keys: {list(final_state.keys())}")
            
            answer = final_state.get('final_answer', "No answer generated by the agent.")
            logger.info(f"📝 Final answer length: {len(answer)} characters")
            
            # Log any errors
            if 'error' in final_state and final_state['error']:
                logger.warning(f"⚠️  Agent reported error: {final_state['error']}")
            
            return answer
        except Exception as e:
            logger.error(f"❌ Deep research agent failed: {e}", exc_info=True)
            raise
